### ISSUE TITLE
Listening progress bar

### ISSUE THREAD

**Issue by hrueschwein** [patryk-ku/mpris-discord-rpc#11]
At first, thank you for this tool, it's a pleasure to use it =)

Recently, Discord added ability to use a listening progress bar (similar to the one used by Spotify integration) for all DRPC applications ([proof](https://github.com/Senophyx/Discord-RPC/issues/28#issuecomment-2301287350)).

Would be nice if this tool had such an opportunity too =)

**Comment by patryk-ku** [comment]
If the Discord RPC library I use has such an option, I will add it right away.

**Comment by patryk-ku** [comment]
Ok, done:

![image](https://github.com/user-attachments/assets/6f3a2cac-5912-4c33-b526-7bbdec2dbaf2)

If the music player provides information about the duration and current position of the song, it will look like this.

It's ready for download on the release page. Thanks for letting me know that Discord has made this option available. Now the custom music status looks way better.

**Comment by hrueschwein** [comment]
Thank you! :)
