### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by Blackilykat** [patryk-ku/mpris-discord-rpc#8]
The github release says it's version  `0.1.3`, but running `./mpris-discord-rpc --version` shows `0.1.1`
![image](https://github.com/user-attachments/assets/07139bdb-1cb1-41b4-a931-d91b5b04d687)

**Comment by patryk-ku** [comment]
Well, I forgot to update the version number in the `Cargo.toml` file here:

https://github.com/patryk-ku/mpris-discord-rpc/blob/8119dd1273c2ce06f78a90a56384405fdbb51229/Cargo.toml#L3

I will fix this in the next version, which will come out soon. Thanks for pointing this out.

**Comment by patryk-ku** [comment]
Fixed in [v0.1.4](https://github.com/patryk-ku/mpris-discord-rpc/releases/tag/v0.1.4)
